import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Theme from "@/providers/theme";
import Toast from "@/components/common/toasts/toast";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${openSans.className} bg-bg-primary`}
      >
        <Theme>
          {children}
        </Theme>

        <Toast />
      </body>
    </html>
  );
}
